#!/bin/bash
# compile debug


# echo "GCC"
# g++-14 -std=c++20 -O0 -Wno-non-template-friend -ftemplate-depth=100 -ftemplate-backtrace-limit=0 main.cpp -o __run__

echo "CLANG"
clang++-19 -std=c++20 -O0 -ftemplate-depth=1000 -ftemplate-backtrace-limit=0 main.cpp -o __run__

endl=""
args=""

if test -f __run__
then
echo "It COMPILES! MUAHAHAHAHAHAHA"
chmod 777 __run__
echo "$args"
echo "$endl"
echo "$args" | ./__run__
rm __run__;
fi